apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: industrial-edge-tst-all
  namespace: industrial-edge-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - industrial-edge-tst-all
