---
global:
  pattern: hybrid-mesh-platform
  singleArgoCD: true
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
