main:
  clusterGroupName: east
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
    helmRepoUrl: https://charts.validatedpatterns.io
clusterGroup:
  name: east
  namespaces:
    industrial-edge-tst-all: {}
    industrial-edge-stormshift-messaging: {}
    industrial-edge-ml-workspace: {}
    industrial-edge-ci: {}
    ml-development: {}
    industrial-edge-data-lake: {}
    stackrox: {}
    devspaces: {}
    camel-dashboard: {}
    spoke-gateway-system: {}
    neuroface-cv: {}
    service-interconnect: {}
    kairos-system:
      operatorGroup: true
      targetNamespaces:
        - kairos-system
    openshift-cluster-observability-operator: {}
    openshift-opentelemetry: {}
    istio-system: {}
    redhat-connectivity-link-operator: {}
    redhat-ods-operator:
      operatorGroup: true
      targetNamespaces: []
    redhat-ods-applications: {}
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets: {}
  subscriptions:
    amq-broker-rhel8:
      name: amq-broker-rhel8
      namespace: openshift-operators
      channel: 7.12.x
      source: redhat-operators
    camel-k:
      name: camel-k
      namespace: openshift-operators
      channel: stable-v2
      source: community-operators
    amq-streams:
      name: amq-streams
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    devspaces:
      name: devspaces
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    kubernetes-imagepuller-operator:
      name: kubernetes-imagepuller-operator
      namespace: openshift-operators
      channel: stable
      source: community-operators
    rhacs-operator:
      name: rhacs-operator
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    skupper-operator:
      name: skupper-operator
      namespace: openshift-operators
      channel: stable-2
      source: redhat-operators
    grafana-operator:
      name: grafana-operator
      namespace: openshift-operators
      channel: v5
      source: community-operators
    opentelemetry-product:
      name: opentelemetry-product
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    kiali-ossm:
      name: kiali-ossm
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    rhods-operator:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-3.4
      source: redhat-operators
    servicemeshoperator3:
      name: servicemeshoperator3
      namespace: openshift-operators
      channel: stable-3.2
      source: redhat-operators
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
  argoProjects:
  - platform
  - operators-edge
  - security
  - mesh
  - observability
  - industrial-edge
  - workshop
  - external-secrets
  - fleet-pull
  sharedValueFiles:
  - /overrides/values-{{ $.Values.global.clusterPlatform }}.yaml
  - /overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name
    }}.yaml
  applications:
    openshift-gitops:
      name: openshift-gitops
      namespace: openshift-gitops
      argoProject: platform
      syncWave: '0'
      path: charts/all/openshift-gitops
    platform-users:
      name: platform-users
      namespace: openshift-gitops
      argoProject: platform
      syncWave: '0'
      path: charts/all/platform-users
    fleet-values-sync:
      name: fleet-values-sync
      namespace: openshift-gitops
      argoProject: fleet-pull
      syncWave: '5'
      path: charts/all/fleet-values-sync
    namespaces:
      name: namespaces
      namespace: openshift-gitops
      argoProject: platform
      syncWave: '1'
      path: charts/all/namespaces
    kairos:
      name: kairos
      namespace: kairos-system
      argoProject: security
      syncWave: '3'
      path: charts/all/kairos
    camel-dashboard-openshift:
      name: camel-dashboard-openshift
      namespace: camel-dashboard
      argoProject: industrial-edge
      syncWave: '3'
      path: charts/all/camel-dashboard-openshift
    servicemeshoperator3:
      name: servicemeshoperator3
      namespace: istio-system
      argoProject: mesh
      syncWave: '4'
      path: charts/all/servicemeshoperator3
    observability:
      name: observability
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      syncWave: '4'
      path: charts/all/observability
    acs-secured-cluster:
      name: acs-secured-cluster
      namespace: stackrox
      argoProject: security
      syncWave: '4'
      path: charts/all/acs-secured-cluster
    spoke-dashboards:
      name: spoke-dashboards
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      syncWave: '4'
      path: charts/all/spoke-dashboards
    istio-monitoring:
      name: istio-monitoring
      namespace: istio-system
      argoProject: observability
      syncWave: '4'
      path: charts/all/istio-monitoring
      overrides:
        - name: clusterSuffix
          value: "-east"
    opentelemetry:
      name: opentelemetry
      namespace: openshift-opentelemetry
      argoProject: observability
      syncWave: '4'
      path: charts/all/opentelemetry
    rhcl-operator:
      name: rhcl-operator
      namespace: redhat-connectivity-link-operator
      argoProject: mesh
      syncWave: '3'
      path: charts/all/rhcl-operator
    kiali:
      name: kiali
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      syncWave: '4'
      path: charts/all/kiali
    industrial-edge-tst:
      name: industrial-edge-tst
      namespace: industrial-edge-tst-all
      argoProject: industrial-edge
      syncWave: '5'
      path: charts/all/industrial-edge-tst
      overrides:
        - name: clusterName
          value: east
        - name: global.hubClusterDomain
          value: '{{ $.Values.global.hubClusterDomain }}'
    industrial-edge-stormshift:
      name: industrial-edge-stormshift
      namespace: industrial-edge-stormshift-messaging
      argoProject: industrial-edge
      syncWave: '5'
      path: charts/all/industrial-edge-stormshift
      overrides:
        - name: clusterName
          value: east
    industrial-edge-pipelines:
      name: industrial-edge-pipelines
      namespace: industrial-edge-ci
      argoProject: industrial-edge
      syncWave: '5'
      path: charts/all/industrial-edge-pipelines
    industrial-edge-data-science-cluster:
      name: industrial-edge-data-science-cluster
      namespace: redhat-ods-applications
      argoProject: industrial-edge
      syncWave: '7'
      path: charts/all/industrial-edge-data-science-cluster
    industrial-edge-data-lake:
      name: industrial-edge-data-lake
      namespace: industrial-edge-data-lake
      argoProject: industrial-edge
      syncWave: '5'
      path: charts/all/industrial-edge-data-lake
      overrides:
        - name: clusterName
          value: east
    industrial-edge-data-science-project:
      name: industrial-edge-data-science-project
      namespace: ml-development
      argoProject: industrial-edge
      syncWave: '5'
      path: charts/all/industrial-edge-data-science-project
    ie-anomaly-alerter:
      name: ie-anomaly-alerter
      namespace: industrial-edge-tst-all
      argoProject: industrial-edge
      syncWave: '6'
      path: charts/all/ie-anomaly-alerter
    spoke-gateway:
      name: spoke-gateway
      namespace: spoke-gateway-system
      argoProject: mesh
      syncWave: '6'
      path: charts/all/spoke-gateway
    spoke-interconnect:
      name: spoke-interconnect
      namespace: service-interconnect
      argoProject: mesh
      syncWave: '8'
      path: charts/all/spoke-interconnect
      overrides:
        - name: clusterName
          value: east
    spoke-neuroface-cv:
      name: spoke-neuroface-cv
      namespace: neuroface-cv
      argoProject: mesh
      syncWave: '9'
      path: charts/all/spoke-neuroface-cv
      overrides:
        - name: clusterName
          value: east
    devspaces:
      name: devspaces
      namespace: devspaces
      argoProject: workshop
      syncWave: '7'
      path: charts/all/devspaces
    console-links:
      name: console-links
      namespace: openshift-gitops
      argoProject: workshop
      syncWave: '9'
      path: charts/all/console-links
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
      syncWave: '3'
    operators-edge:
      name: operators-edge
      namespace: openshift-operators
      argoProject: operators-edge
      path: charts/all/operators-edge
      syncWave: '2'
gitops:
  repoURL: https://github.com/maximilianoPizarro/hybrid-mesh-platform
  revision: main
global:
  pattern: hybrid-mesh-platform
  vpArgoNamespace: openshift-gitops
