apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: Software Templates for Developer Hub
spec:
  targets:
    - ./industrial-edge.yaml
    - ./industrial-edge-camel-kaoto.yaml
    - ./camel-kaoto-cdc.yaml
    - ./industrial-edge-delete.yaml
    - ./industrial-edge-api-product.yaml
    - ./openshift-ai-workspace.yaml
    - ./cnv-vm-workshop.yaml
    - ./ai-computer-vision.yaml
