clusterDomain: ""
gitops:
  repoUrl: ""
  revision: "main"
  strategies:
    push:
      enabled: true
      applicationSetName: fleet-spoke-push
      componentIds:
        - operators-ci
        - operators-platform
    pull:
      enabled: true
clusters:
  hub:
    domain: ""
  east:
    domain: ""
  west:
    domain: ""
managedClusters:
  east:
    apiUrl: ""
    domain: ""
    token: ""
  west:
    apiUrl: ""
    domain: ""
    token: ""
