apiVersion: v2
name: hybrid-mesh-platform-hub
description: RHDP bootstrap for hub cluster (clustergroup Application)
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Maximiliano Pizarro
    email: developer@redhat.com
