main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
    helmRepoUrl: https://charts.validatedpatterns.io
clusterGroup:
  name: hub
  namespaces:
    stackrox: {}
    openshift-gitops: {}
    developer-hub: {}
    hub-gateway-system: {}
    workshop-kuadrant-apis: {}
    mcp-system: {}
    gitea: {}
    service-interconnect: {}
    mailpit: {}
    mailpit-templates: {}
    industrial-edge-ml-workspace: {}
    kafka-console: {}
    quay-registry: {}
    kubecost: {}
    maas-workshop: {}
    showroom: {}
    neuroface: {}
    cnv-workshop: {}
    openshift-cnv: {}
    redhat-connectivity-link-operator: {}
    openshift-cluster-observability-operator: {}
    openshift-opentelemetry: {}
    distributed-tracing: {}
    istio-system: {}
    kairos-system: {}
    redhat-ods-operator: {}
    redhat-ods-applications: {}
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets: {}
    vault: {}
  subscriptions:
    cluster-observability-operator:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator
      channel: stable
      source: redhat-operators
    grafana-operator:
      name: grafana-operator
      namespace: openshift-operators
      channel: v5
      source: community-operators
    kiali-ossm:
      name: kiali-ossm
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    camel-k:
      name: camel-k
      namespace: openshift-operators
      channel: stable-v2
      source: community-operators
    rhods-operator:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-2.25
      source: redhat-operators
    serverless-operator:
      name: serverless-operator
      namespace: openshift-serverless
      channel: stable
      source: redhat-operators
    amq-streams:
      name: amq-streams
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    amq-streams-console:
      name: amq-streams-console
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    opentelemetry-product:
      name: opentelemetry-product
      namespace: openshift-operators
      channel: stable
      source: redhat-operators
    tempo-product:
      name: tempo-product
      namespace: openshift-tempo-operator
      channel: stable
      source: redhat-operators
    rhdh:
      name: rhdh
      namespace: openshift-operators
      channel: fast-1.9
      source: redhat-operators
    skupper-operator:
      name: skupper-operator
      namespace: openshift-operators
      channel: stable-2
      source: redhat-operators
    servicemeshoperator3:
      name: servicemeshoperator3
      namespace: openshift-operators
      channel: stable-3.2
      source: redhat-operators
    quay-operator:
      name: quay-operator
      namespace: openshift-operators
      channel: stable-3.14
      source: redhat-operators
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
  argoProjects:
  - platform
  - operators-platform
  - fleet
  - fleet-push
  - fleet-pull
  - security
  - mesh
  - observability
  - workshop
  - ai
  - external-secrets
  sharedValueFiles:
  - /overrides/values-{{ $.Values.global.clusterPlatform }}.yaml
  - /overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name
    }}.yaml
  applications:
    platform-users:
      name: platform-users
      namespace: openshift-gitops
      argoProject: platform
      path: charts/all/platform-users
      syncWave: '0'
    openshift-gitops:
      name: openshift-gitops
      namespace: openshift-gitops
      argoProject: platform
      path: charts/all/openshift-gitops
      syncWave: '0'
    namespaces:
      name: namespaces
      namespace: openshift-gitops
      argoProject: platform
      path: charts/all/namespaces
      syncWave: '0'
    kairos:
      name: kairos
      namespace: kairos-system
      argoProject: security
      path: charts/all/kairos
      syncWave: '3'
    servicemeshoperator3:
      name: servicemeshoperator3
      namespace: istio-system
      argoProject: mesh
      path: charts/all/servicemeshoperator3
      syncWave: '4'
    acm-operator:
      name: acm-operator
      namespace: open-cluster-management
      argoProject: fleet
      path: charts/all/acm-operator
      syncWave: '0'
    acs-operator:
      name: acs-operator
      namespace: stackrox
      argoProject: security
      path: charts/all/acs-operator
      syncWave: '0'
    acs-init-bundle-sync:
      name: acs-init-bundle-sync
      namespace: stackrox
      argoProject: security
      path: charts/all/acs-init-bundle-sync
      syncWave: '7'
    developer-hub:
      name: developer-hub
      namespace: developer-hub
      argoProject: workshop
      path: charts/all/developer-hub
      syncWave: '0'
    acm-hub-spoke:
      name: acm-hub-spoke
      namespace: openshift-gitops
      argoProject: fleet
      path: charts/all/acm-hub-spoke
      syncWave: '6'
    fleet-values-sync:
      name: fleet-values-sync
      namespace: openshift-gitops
      argoProject: fleet
      path: charts/all/fleet-values-sync
      syncWave: '5'
    observability:
      name: observability
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      path: charts/all/observability
      syncWave: '0'
    kiali:
      name: kiali
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      path: charts/all/kiali
      syncWave: '0'
    opentelemetry:
      name: opentelemetry
      namespace: openshift-opentelemetry
      argoProject: observability
      path: charts/all/opentelemetry
      syncWave: '0'
    distributed-tracing:
      name: distributed-tracing
      namespace: distributed-tracing
      argoProject: observability
      path: charts/all/distributed-tracing
      syncWave: '5'
    rhcl-operator:
      name: rhcl-operator
      namespace: redhat-connectivity-link-operator
      argoProject: mesh
      path: charts/all/rhcl-operator
      syncWave: '1'
    hub-gateway:
      name: hub-gateway
      namespace: hub-gateway-system
      argoProject: mesh
      path: charts/all/hub-gateway
      syncWave: '5'
    workshop-kuadrant-apis:
      name: workshop-kuadrant-apis
      namespace: workshop-kuadrant-apis
      argoProject: workshop
      path: charts/all/workshop-kuadrant-apis
      syncWave: '6'
    mcp-gateway:
      name: mcp-gateway
      namespace: mcp-system
      argoProject: workshop
      path: charts/all/mcp-gateway
      syncWave: '2'
    gitea-chart:
      name: gitea-chart
      namespace: gitea
      argoProject: workshop
      repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 12.5.0
      syncWave: '0'
      values:
        gitea:
          admin:
            username: gitea_admin
            password: openshift
            passwordMode: keepUpdated
    gitea:
      name: gitea
      namespace: gitea
      argoProject: workshop
      path: charts/all/gitea
      syncWave: '0'
    console-links:
      name: console-links
      namespace: openshift-gitops
      argoProject: workshop
      path: charts/all/console-links
      syncWave: '10'
    grafana-dashboards:
      name: grafana-dashboards
      namespace: openshift-cluster-observability-operator
      argoProject: observability
      path: charts/all/grafana-dashboards
      syncWave: '0'
    istio-monitoring:
      name: istio-monitoring
      namespace: istio-system
      argoProject: observability
      path: charts/all/istio-monitoring
      syncWave: '0'
      overrides:
        - name: workshopGateways.enabled
          value: "true"
    service-interconnect:
      name: service-interconnect
      namespace: service-interconnect
      argoProject: mesh
      path: charts/all/service-interconnect
      syncWave: '3'
    mailpit:
      name: mailpit
      namespace: mailpit
      argoProject: workshop
      path: charts/all/mailpit
      syncWave: '0'
    mailpit-templates:
      name: mailpit-templates
      namespace: mailpit-templates
      argoProject: workshop
      path: charts/all/mailpit-templates
      syncWave: '0'
    industrial-edge-minio:
      name: industrial-edge-minio
      namespace: industrial-edge-ml-workspace
      argoProject: ai
      path: charts/all/industrial-edge-minio
      syncWave: '0'
    kafka-console:
      name: kafka-console
      namespace: kafka-console
      argoProject: observability
      path: charts/all/kafka-console
      syncWave: '4'
    skupper-network-observer:
      name: skupper-network-observer
      namespace: service-interconnect
      argoProject: mesh
      path: charts/all/skupper-network-observer
      syncWave: '4'
    quay-registry:
      name: quay-registry
      namespace: quay-registry
      argoProject: workshop
      path: charts/all/quay-registry
      syncWave: '0'
    kubecost:
      name: kubecost
      namespace: kubecost
      argoProject: observability
      path: charts/all/kubecost
      syncWave: '0'
    openshift-ai-hub:
      name: openshift-ai-hub
      namespace: maas-workshop
      argoProject: ai
      path: charts/all/openshift-ai-hub
      syncWave: '5'
    workshop-registration:
      name: workshop-registration
      namespace: showroom
      argoProject: workshop
      path: charts/all/workshop-registration
      syncWave: '4'
    showroom:
      name: showroom
      namespace: showroom
      argoProject: workshop
      path: charts/all/showroom
      syncWave: '5'
    workshop-demos:
      name: workshop-demos
      namespace: developer-hub
      argoProject: workshop
      path: charts/all/workshop-demos
      syncWave: '6'
    neuroface:
      name: neuroface
      namespace: neuroface
      argoProject: ai
      path: charts/all/neuroface
      syncWave: '7'
      overrides:
        - name: neuroface.route.host
          value: neuroface.{{ $.Values.global.localClusterDomain }}
    cnv-example:
      name: cnv-example
      namespace: cnv-workshop
      argoProject: ai
      path: charts/all/cnv-example
      syncWave: '8'
    vault:
      name: vault
      namespace: vault
      argoProject: external-secrets
      chart: hashicorp-vault
      chartVersion: 0.1.*
      syncWave: '2'
    vault-demo-auth:
      name: vault-demo-auth
      namespace: vault
      argoProject: external-secrets
      path: charts/all/vault-demo-auth
      syncWave: '3'
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
      syncWave: '2'
    operators-platform:
      name: operators-platform
      namespace: openshift-operators
      argoProject: operators-platform
      path: charts/all/operators-platform
      syncWave: '1'
    fleet-pull-overview:
      name: fleet-pull-overview
      namespace: openshift-gitops
      argoProject: fleet-pull
      path: charts/all/fleet-pull-overview
      syncWave: '1'
    platform-validation:
      name: platform-validation
      namespace: openshift-gitops
      argoProject: platform
      path: charts/all/platform-validation
      syncWave: '99'
  managedClusterGroups:
    east:
      name: east
      acmlabels:
      - name: clusterGroup
        value: east
    west:
      name: west
      acmlabels:
      - name: clusterGroup
        value: west
gitops:
  repoURL: https://github.com/maximilianoPizarro/hybrid-mesh-platform
  revision: main
global:
  pattern: hybrid-mesh-platform
  vpArgoNamespace: openshift-gitops
