apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: neuroface-cv-east
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: neuroface-cv-east
  host: neuroface-cv-east
  port: 8080
