{{- if .Values.industrialEdge.enabled }}
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-east-stormshift
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-east-stormshift
  host: kafka-east-stormshift
  port: 9092
{{- end }}
