clusterRole: spoke
subscriptions:
  - name: camel-k
    namespace: openshift-operators
    channel: stable-v2
    source: community-operators
  - name: devspaces
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: kubernetes-imagepuller-operator
    namespace: openshift-operators
    channel: stable
    source: community-operators
