apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fleet-spoke-push
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform-hub-spoke
    platform.io/gitops-strategy: push
    cluster.open-cluster-management.io/placement: hub-spoke-placement
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    apps.open-cluster-management.io/source-repository: {{ include "acm-hub-spoke.gitopsRepoUrl" . | quote }}
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: hub-spoke-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{`{{name}}-spoke-components`}}'
      labels:
        app.kubernetes.io/part-of: platform-hub-spoke
        platform.io/gitops-strategy: push
        apps.open-cluster-management.io/cluster-set: global
        apps.open-cluster-management.io/ocm-managed-cluster: '{{`{{name}}`}}'
        cluster.open-cluster-management.io/placement: hub-spoke-placement
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{`{{name}}`}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        platform.io/gitops-strategy: push
    spec:
      project: fleet-push
      source:
        repoURL: {{ include "acm-hub-spoke.gitopsRepoUrl" . }}
        targetRevision: {{ include "acm-hub-spoke.gitopsRevision" . | quote }}
        path: charts/all/spoke-meta-push
        helm:
          valuesObject:
            clusterName: '{{`{{name}}`}}'
            clusterRole: spoke
            gitops:
              repoUrl: {{ include "acm-hub-spoke.gitopsRepoUrl" . | quote }}
              revision: {{ include "acm-hub-spoke.gitopsRevision" . | quote }}
            hubClusterDomain: {{ .Values.clusters.hub.domain | default (include "acm-hub-spoke.hubClusterDomain" .) | quote }}
            eastDomain: {{ .Values.clusters.east.domain | default "" | quote }}
            westDomain: {{ .Values.clusters.west.domain | default "" | quote }}
      destination:
        name: '{{`{{name}}`}}'
        namespace: openshift-gitops
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
