apiVersion: v2
name: neuroface-platform
description: NeuroFace workshop demo (Helm wrapper for upstream neuroface chart)
type: application
version: 0.2.1
appVersion: "1.5.0"
dependencies:
  - name: neuroface
    version: 1.4.1
    repository: https://maximilianopizarro.github.io/neuroface/
