clusterRole: spoke
subscriptions:
  - name: servicemeshoperator3
    namespace: openshift-operators
    channel: stable-3.2
    source: redhat-operators
  - name: amq-broker-rhel8
    namespace: openshift-operators
    channel: 7.12.x
    source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: rhods-operator
    namespace: redhat-ods-operator
    channel: stable-2.25
    source: redhat-operators
  # Merged from operators-ci (CI/CD + DevSpaces)
  - name: camel-k
    namespace: openshift-operators
    channel: stable-v2
    source: community-operators
  - name: devspaces
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: kubernetes-imagepuller-operator
    namespace: openshift-operators
    channel: stable
    source: community-operators
