apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroface-frontend
  namespace: ${{ values.name }}-${{ values.owner }}
  labels:
    app: neuroface-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuroface-frontend
  template:
    metadata:
      labels:
        app: neuroface-frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/maximilianopizarro/neuroface-frontend:v1.5.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: neuroface-frontend
  namespace: ${{ values.name }}-${{ values.owner }}
spec:
  selector:
    app: neuroface-frontend
  ports:
    - port: 8080
      targetPort: 8080
