apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.name }}-${{ values.owner }}
  labels:
    app.kubernetes.io/part-of: neuroface
    kubecost.io/team: neuroface
    kubecost.io/product: ai-vision
