apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-credentials
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: {{ .Values.adminUser | quote }}
  password: {{ .Values.adminPassword | quote }}
