apiVersion: v1
kind: Secret
metadata:
  name: tempo-minio
  namespace: distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  bucket: {{ .Values.minio.bucket | quote }}
  endpoint: {{ .Values.minio.endpoint | quote }}
  access_key_id: {{ .Values.minio.accessKey | quote }}
  access_key_secret: {{ .Values.minio.secretKey | quote }}
