apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}-osai
  title: OpenShift AI — ${{ values.name }}
  description: Data Science workspace using MaaS model ${{ values.model }}
  annotations:
    openshift.ai/project: ${{ values.name }}
    maas.redhat.com/default-model: ${{ values.model }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-cluster: hub
    backstage.io/kubernetes-id: ${{ values.name }}-osai
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton: ${{ values.namespace }}
    gitlab.com/project-slug: ws-${{ values.owner }}/${{ values.name }}-osai
    quay.io/repository-slug: workshop/${{ values.owner }}-${{ values.name }}-osai
  links:
    - url: https://rh-ai.apps.${{ values.clusterDomain }}
      title: OpenShift AI Dashboard
      icon: dashboard
spec:
  type: ml-workspace
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: openshift-ai-workshop
  dependsOn:
    - component:ai-gateway-maas
  consumesApis:
    - workshop-maas-openapi
