{{- $appsDomain := include "gitlab-operator.appsDomain" . -}}
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  chart:
    version: {{ .Values.gitlab.chartVersion | quote }}
    values:
      global:
        hosts:
          domain: {{ $appsDomain | quote }}
          hostSuffix: gitlab
          https: true
        ingress:
          configureCertmanager: false
          class: openshift-default
          tls:
            enabled: false
        openshift:
          enabled: true
          route:
            enabled: true
            tls:
              termination: edge
        minio:
          enabled: true
      certmanager:
        install: false
      installCertmanager: false
      nginx-ingress:
        enabled: false
      prometheus:
        install: false
      registry:
        enabled: {{ .Values.gitlab.registryEnabled }}
      gitlab:
        webservice:
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              memory: 2Gi
        gitaly:
          persistence:
            size: {{ .Values.gitlab.gitalyStorage | quote }}
        toolbox:
          backups:
            cron:
              enabled: false
      postgresql:
        persistence:
          size: {{ .Values.gitlab.postgresStorage | quote }}
